---
- name: Configure EKS cluster with Prometheus and Grafana
  hosts: localhost
  tasks:
    - name: Install kubectl
      ansible.builtin.command: >
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      args:
        creates: /usr/local/bin/kubectl

    - name: Apply Kubernetes manifests for Prometheus and Grafana
      ansible.builtin.command: >
        kubectl apply -f /path/to/prometheus-grafana-config.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Deploy Flask app using Kubernetes
      ansible.builtin.command: >
        kubectl apply -f /path/to/deployment.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
