name: Provision EKS and Deploy App

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

  ansible:
    name: Configure Cluster with Ansible
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbook.yml

  deploy:
    name: Deploy Flask Application
    runs-on: ubuntu-latest
    needs: ansible

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t flask-app ./flask-app
          docker tag flask-app:latest <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/flask-app:latest
          docker push <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/flask-app:latest

      - name: Deploy to EKS
        run: kubectl apply -f k8s/flask_app_deployment.yaml
