name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        
  ansible:
    name: Configure Cluster with Ansible
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbook.yml

  deploy:
    name: Deploy Flask Application
    runs-on: ubuntu-latest
    needs: ansible

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t flask-app ./flask-app
          docker tag flask-app:latest <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/flask-app:latest
          docker push <your-aws-account-id>.dkr.ecr.<region>.amazonaws.com/flask-app:latest

      - name: Deploy to EKS
        run: kubectl apply -f k8s/flask_app_deployment.yaml
