name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve
        
  ansible:
    name: Configure Cluster with Ansible
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbook.yml

  deploy:
    name: Deploy Flask Application
    runs-on: ubuntu-latest
    needs: ansible

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Check if ECR repository exists and create if not
        run: |
          REPO_NAME=flask-app
          if ! aws ecr describe-repositories --repository-names $REPO_NAME --region ${{ secrets.AWS_DEFAULT_REGION }} > /dev/null 2>&1; then
            echo "Repository does not exist. Creating repository..."
            aws ecr create-repository --repository-name $REPO_NAME --region ${{ secrets.AWS_DEFAULT_REGION }}
          else
            echo "Repository already exists."
          fi

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin <your-aws-account-id>.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t flask-app ./flask-app
          docker tag flask-app:latest <your-aws-account-id>.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/flask-app:latest
          docker push <your-aws-account-id>.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/flask-app:latest

      - name: Deploy to EKS
        run: kubectl apply -f k8s/flask_app_deployment.yaml
